apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: cron-input-kafka-output
spec:
  version: "v2.0.0"
  image: openfunctiondev/cron-input-kafka-output-java:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/builder-java:v2-11
    env:
      FUNC_NAME: "dev.openfunction.samples.OpenFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/wanjunlei/functions-framework-java.git"
      sourceSubPath: "samples"
      revision: "java"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    outputs:
      - name: kafka-server
        type: bindings.kafka
        operation: "create"
    bindings:
      cron:
        type: bindings.cron
        version: v1
        metadata:
          - name: schedule
            value: "@every 2s"
      kafka-server:
        type: bindings.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: topics
            value: "sample-topic"
          - name: consumerGroup
            value: "bindings-with-output"
          - name: publishTopic
            value: "sample-topic"
          - name: authRequired
            value: "false"
    triggers:
      dapr:
        - name: cron
          type: bindings.cron
    hooks:
      post:
        - dev.openfunction.samples.hooks.ExampleHook
      pre:
        - dev.openfunction.samples.hooks.ExampleHook