apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: function-cloudevent
spec:
  version: "v2.0.0"
  image: "openfunctiondev/function-cloudevent-java:v1"
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/builder-java:v2-18
    env:
      FUNC_NAME: "dev.openfunction.samples.CloudEventFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/wanjunlei/functions-framework-java.git"
      sourceSubPath: "samples"
      revision: "java"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    hooks:
      post:
        - dev.openfunction.samples.hooks.ExampleHook
      pre:
        - dev.openfunction.samples.hooks.ExampleHook