apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: http-with-output
  annotations:
    plugins: |
      pre:
      - dev.openfunction.samples.plugins.ExamplePlugin
      post:
      - dev.openfunction.samples.plugins.ExamplePlugin
spec:
  version: "v2.0.0"
  image: "openfunctiondev/http-with-output-java:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunctiondev/builder-java:v2-17
    env:
      FUNC_NAME: "dev.openfunction.samples.OpenFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/wanjunlei/functions-framework-java.git"
      sourceSubPath: "samples"
      revision: "java"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    runtime: "knative"
    outputs:
      - name: sample
        component: kafka-server
        operation: "create"
    bindings:
      kafka-server:
        type: bindings.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: topics
            value: "sample-topic"
          - name: consumerGroup
            value: "bindings-with-output"
          - name: publishTopic
            value: "sample-topic"
          - name: authRequired
            value: "false"
