apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
  annotations:
    plugins: |
      pre:
      - dev.openfunction.samples.plugins.ExamplePlugin
      post:
      - dev.openfunction.samples.plugins.ExamplePlugin
spec:
  version: "v2.0.0"
  image: "openfunctiondev/sample-go-func-java:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunctiondev/builder-java:v2-17
    env:
      FUNC_NAME: "dev.openfunction.samples.HttpFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/wanjunlei/functions-framework-java.git"
      sourceSubPath: "samples"
      revision: "java"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    runtime: "knative"
