apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: autoscaling-subscriber
spec:
  version: "v2.0.0"
  image: openfunctiondev/autoscaling-subscriber-java:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/builder-java:v2-16
    env:
      FUNC_NAME: "dev.openfunction.samples.OpenFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
      # Use FUNC_GOPROXY to set the goproxy
      # FUNC_GOPROXY: "https://goproxy.cn"
    srcRepo:
      url: "https://github.com/wanjunlei/functions-framework-java.git"
      sourceSubPath: "samples"
      revision: "java"
  serving:
    scaleOptions:
      keda:
        triggers:
          - type: kafka
            metadata:
              topic: "sample-topic"
              bootstrapServers: kafka-server-kafka-brokers.default.svc.cluster.local:9092
              consumerGroup: autoscaling-subscriber
              lagThreshold: "20"
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 60
          advanced:
            horizontalPodAutoscalerConfig:
              behavior:
                scaleDown:
                  stabilizationWindowSeconds: 45
                  policies:
                    - type: Percent
                      value: 50
                      periodSeconds: 15
                scaleUp:
                  stabilizationWindowSeconds: 0
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    pubsub:
      kafka-server:
        type: pubsub.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: authRequired
            value: "false"
          - name: allowedTopics
            value: "sample-topic"
          - name: consumerID
            value: "autoscaling-subscriber"
    triggers:
      dapr:
        - name: kafka-server
          type: bindings.cron
          topic: "sample-topic"
    hooks:
      post:
        - dev.openfunction.samples.hooks.ExampleHook
      pre:
        - dev.openfunction.samples.hooks.ExampleHook