name: Maven Publish
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths:
      - '.github/workflows/**'
      - 'functions-framework-api/pom.xml'
      - 'functions-framework-api/src/**'
      - 'functions-framework-invoker/pom.xml'
      - 'functions-framework-invoker/src/main/**'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish framework API
        uses: samuelmeuli/action-maven-publish@v1
        with:
          directory: functions-framework-api
          gpg_private_key: ${{ secrets.GPG_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Publish framework invoker
        uses: samuelmeuli/action-maven-publish@v1
        with:
          directory: functions-framework-invoker
          gpg_private_key: ${{ secrets.GPG_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
